resources:
- ../bases/
patches:
- patch: |-
    - op: replace
      path: /spec/template/spec/containers/0/env/1
      value:
        name: RELATED_IMAGE_HYPERFLEET_API
        value: quay.io/redhat-services-prod/hyperfleet-tenant/hyperfleet/hyperfleet-api@sha256:f3d11afc53b5480ffc906bc81fd5a90d05c2856e04ff378a06e332968adc17b9
    - op: replace
      path: /spec/template/spec/containers/0/env/2
      value:
        name: RELATED_IMAGE_HYPERFLEET_OPERATOR
        value: quay.io/redhat-services-prod/hyperfleet-tenant/hyperfleet/hyperfleet-operator@sha256:1bfd468d31f5424237043c179ecd163b959016ce780d7888d81621c68edf8c23
    - op: replace
      path: /spec/template/spec/containers/0/image
      value: quay.io/redhat-services-prod/hyperfleet-tenant/hyperfleet/hyperfleet-operator@sha256:1bfd468d31f5424237043c179ecd163b959016ce780d7888d81621c68edf8c23
  target:
    kind: Deployment
    name: controller-manager