resources:
- ../bases/
patches:
- patch: |-
    - op: replace
      path: /spec/template/spec/containers/0/env/1
      value:
        name: RELATED_IMAGE_HYPERFLEET_API
        value: quay.io/redhat-services-prod/hyperfleet-tenant/hyperfleet/hyperfleet-api@sha256:25722807f515498a597af3a6a161e5ed626800d191f975dd15d89f36774c9d3b
    - op: replace
      path: /spec/template/spec/containers/0/env/2
      value:
        name: RELATED_IMAGE_HYPERFLEET_OPERATOR
        value: quay.io/redhat-services-prod/hyperfleet-tenant/hyperfleet/hyperfleet-operator@sha256:4eea4ab65def91fb944d01d2836382d459feac6679281ebce1544260cf48013c
    - op: replace
      path: /spec/template/spec/containers/0/image
      value: quay.io/redhat-services-prod/hyperfleet-tenant/hyperfleet/hyperfleet-operator@sha256:4eea4ab65def91fb944d01d2836382d459feac6679281ebce1544260cf48013c
  target:
    kind: Deployment
    name: controller-manager