resources:
- ../bases/
patches:
- patch: |-
    - op: replace
      path: /spec/template/spec/containers/0/env/1
      value:
        name: RELATED_IMAGE_HYPERFLEET_API
        value: quay.io/redhat-services-prod/hyperfleet-tenant/hyperfleet/hyperfleet-api@sha256:1d8126a962785b50ccf9a173ba83f1ab0a8bf43247bd9cb1329d57751b09b5a3
    - op: replace
      path: /spec/template/spec/containers/0/env/2
      value:
        name: RELATED_IMAGE_HYPERFLEET_OPERATOR
        value: quay.io/redhat-services-prod/hyperfleet-tenant/hyperfleet/hyperfleet-operator@sha256:c2dd06bef6f5b5b503446f3a43db025ec1346ac9c2600d7eccf330967d804607
    - op: replace
      path: /spec/template/spec/containers/0/image
      value: quay.io/redhat-services-prod/hyperfleet-tenant/hyperfleet/hyperfleet-operator@sha256:c2dd06bef6f5b5b503446f3a43db025ec1346ac9c2600d7eccf330967d804607
  target:
    kind: Deployment
    name: controller-manager